### ISSUE TITLE
Create onboarding content, working group definitions, and intro to project management tools

### ISSUE THREAD

**Issue by agelesspartners** [cure-dao/draft-whitepaper#127]

**Comment by mikepsinn** [comment]
Thanks, @agelesspartners !

Here are some relevant links and ideas about it. 

We've got a tentative list here: 
https://www.notion.so/anonymous-dao/55720d8fb77f4e72928804694a58d0fb?v=b09486e754de49bda09b35775c41b6d4
and here
https://github.com/cure-dao/draft-whitepaper/blob/main/constitution/5-organization.md

We can put them here:
https://github.com/orgs/cure-dao/teams

One option for task management would be Github issues in this repo and tagging the issues with the working group name.  The benefit would be that the tasks are public and available to anyone.  Then we could make links to issues filtered by each working group. 

Another option is using the notion task list here
https://www.notion.so/anonymous-dao/55720d8fb77f4e72928804694a58d0fb?v=b09486e754de49bda09b35775c41b6d4

Here are links to project tools
https://www.notion.so/anonymous-dao/Tools-Guides-74d3e4bf46194dc2a46e29fae96f3f12

It would be nice if we had an onboarding tasks template.  Asana is really nice for that purpose. I have one there already.  Asana's built specifically for tasks and that sort of thing (unlike Notion and Github).  I hate adding another tool but we might consider it if the current options aren't working for people.

**Comment by vincenzodomina** [comment]
Added description and list of steps to be onboarded to github project management to discord start-here channel: 

Vincenzo Domina — heute um 13:40 Uhr
@everyone 
Our current get-involved process:

🤝   HOW TO GET INVOLVED  🤝
⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯
We rely heavily on Github (also for non-coders for project management, don't worry it's not that difficult)

1.  Get an account on https://github.com/
2. Star our Github: https://github.com/cure-dao/
3. Get the free ZenHub extension (to view issues from Github in Kanban boards and Gantt charts -> very cool) 
     https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd
4. Create, comment in Issues and contribute with linked pull requests
     (also for finished documents, presentations, design files Github is very cool for version management)
5. Help prioritize tasks (More Info and howto: 
     https://github.com/cure-dao/draft-whitepaper/blob/main/how-to/task-management/vote-on-tasks-and-sort-by-priority.md)
6. Issues and tasks are assigned, discussed, reported, moved in the specific calls (see Events) to maintain overview and communication 
7. Your contributions are tracked already within your github activity and discord activity and manually tracking your time for now
     (designers don't worry, everything will be weighted accordingly, details coming)

More information to contribution and instructions here: https://github.com/cure-dao/draft-whitepaper/tree/main/how-to

What we still need:
- Bots for onboarding 
- More detailed instructions 
- Compensation definitions, processes, tools
- Roles and working group processes
- Your feedback!

Feel free to post your competences and where you would like to contribute in this channel

**Comment by vincenzodomina** [comment]
Improved "start-here" channel content for online use in e.g. gitbooks  PR #172
