### ISSUE TITLE
Consolidate visuals for a power point

### ISSUE THREAD

**Issue by agelesspartners** [cure-dao/draft-whitepaper#175]
https://github.com/cure-dao/draft-whitepaper/blob/main/assets/cure-dao-powerpoint-presentation.pptx

https://github.com/cure-dao/draft-whitepaper/blob/main/assets

**Comment by mikepsinn** [comment]
https://github.com/cure-dao/draft-whitepaper/blob/main/assets/cure-dao-powerpoint-presentation.pptx

https://github.com/cure-dao/draft-whitepaper/blob/main/assets
